/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * PROBLEM STATEMENT:
 * Implement PWM on Timer8. Increase duty cycle by 10 on each switch press (handle interrupt).
 * Optional part: On next switch press decrease value by 10.
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "pwm.h"
#include "switch_intr.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int16_t ccr;
	SystemInit();
	PWM_Init();
	SwitchInit();

	while(1)
	{
		ccr = 0;
		while(ccr < 100)
		{
			// wait here until Switch is not pressed.
			while(!SwitchExtiFlag);
			ccr += 10;
			TIM8->CCR1 = ccr;
			// reset global flag to detct next switch press.
			SwitchExtiFlag = 0;
			//DelayMs(10);
		}
		//ccr = 100;
		while(ccr > 0) {
			// wait here until Switch is not pressed.
			while(!SwitchExtiFlag);
			ccr -= 10;
			TIM8->CCR1 = ccr;
			// reset global flag to detct next switch press.
			SwitchExtiFlag = 0;
			//DelayMs(1000);
		}
	}
	return 0;
}
