/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "accel.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {

	LIS_Data val;
	LedInit(LED_GREEN_PIN);
	LedInit(LED_BLUE_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);


	SystemInit();
	LIS_Init(); //initialize accel
	while(1) {
		if(LIS_IsDataAvail()) // check if new data avail
		{
			val = LIS_GetData(); // get the new data
			// print value
			/*sprintf(str, "X=%d, Y=%d, Z=%d\r\n", val.x, val.y, val.z);
			UartPuts(str);*/
			if(val.x >= 1000) {
			    LedOn(LED_BLUE_PIN);
			    DelayMs(1000);
			    LedOff(LED_BLUE_PIN);
			}

			if(val.x <= -1000) {
			    LedOn(LED_RED_PIN);
			    DelayMs(1000);
			    LedOff(LED_RED_PIN);
			}

			if(val.y >= 2000) {
			    LedOn(LED_GREEN_PIN);
			    DelayMs(1000);
			    LedOff(LED_GREEN_PIN);
			}

			if(val.y <= -2000) {
			    LedOn(LED_ORANGE_PIN);
			    DelayMs(1000);
			    LedOff(LED_ORANGE_PIN);
			}


			}
		DelayMs(1000);
	}
	return 0;
}
